# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My life that code(but not just) tells
description: "> # //TODO: If I didn't think through, I can't find a good introduction to describe how awesome
I am (solemn face :<), mark it as todo item makes me feel comfortable ....LOL"
baseurl: '' # the subpath of your site, e.g. /blog
url: "http://carmen0208.github.io" # the base hostname & protocol for your site
disqus_shortname: 'carmen0208-github-io'
author:
  name: 'Carmen Liu'
  email: dearsorry442@gmail.com
  facebook_username: carmen.liu.7355
  linkedin_username:  carmen-liu-ninja
  twitter_username: carmen0208
  github_username:  carmen0208

defaults:
  -
    scope:
      path: '/'
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

# gems: ['jekyll-paginate','jekyll-multiple-languages-plugin']
gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'src']

# jekyll-multiple-languages-plugin settings:
languages: ["en", "cn"]
exclude_from_localizations: ["fonts", "images", "js", "src"]
